language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=2.0.*
  - SYMFONY_VERSION=2.1.*
  - SYMFONY_VERSION=dev-master
  - BUZZ_VERSION=0.6
  - BUZZ_VERSION=0.*

before_script:
  - composer require symfony/dependency-injection:${SYMFONY_VERSION} symfony/http-kernel:${SYMFONY_VERSION} symfony/config:${SYMFONY_VERSION} kriswallsmith/buzz:${BUZZ_VERSION}

script: phpunit --coverage-text

notifications:
  email:
    - gremo1982@gmail.com
